server:
  port: 9999
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false

  aop:
    proxy-target-class: true

  #redis
  redis:
    #redis机器ip
    host: 192.168.21.129
    #redis端口
    port: 6379
    #redis密码
    password:
    #redis超时时间（毫秒），如果不设置，取默认值2000
    timeout: 15000
    #最大空闲数
    maxIdle: 300
    #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
    #maxActive=600
    #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
    maxTotal: 1000
    #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
    maxWaitMillis: 1000
    #连接的最小空闲时间 默认1800000毫秒(30分钟)
    minEvictableIdleTimeMillis: 300000
    #每次释放连接的最大数目,默认3
    numTestsPerEvictionRun: 1024
    #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
    timeBetweenEvictionRunsMillis: 30000
    #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    testOnBorrow: true
    #在空闲时检查有效性, 默认false
    testWhileIdle: true
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

logging:
  level:
    root: info
    com.jwh: info
  pattern:
    console: '%p%m%n'

mybatis-plus:
  # mp 别名配置
  #type-aliases-package: cc.mrbird.febs.system.entity,cc.mrbird.febs.generator.entity,cc.mrbird.febs.job.entity
  # xml mapper文件扫描路径
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    #map-underscore-to-camel-case: true
    jdbc-type-for-null: null
  global-config:
    # 取消mybatisplus Banner图
    banner: false
    db-config:   #逻辑删除配置
      logic-not-delete-value: 0
      logic-delete-value: 1




